name: Build Site
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Run Zola
        run: |
          sudo snap install --edge zola
          cd site
          zola build
